[features]
seeds = false
[programs.localnet]
stakan = "6mEpDuNtJojXtHjBjLgjVM9v2incRGtpz6C52uwDxt98"

[programs.devnet]
stakan = "6mEpDuNtJojXtHjBjLgjVM9v2incRGtpz6C52uwDxt98"

[programs.testnet]
stakan = "6mEpDuNtJojXtHjBjLgjVM9v2incRGtpz6C52uwDxt98"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/yury/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
after-build = "cp ./target/idl/stakan.json ./app/src/idl/stakan.json \n cp ./target/types/stakan.ts ./app/src/idl/stakan.ts"
