[features]
seeds = false
[programs.localnet]
stakan = "StakanXf8bymj5JEgJYH4qUQ7xTtoR1W2BeHUbDjCJb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/yury/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
