[features]
seeds = false
[programs.localnet]
stakan = "C5WmRvAk9BBWyg3uSEZ4EHtrNVn7jZu7qgykckXxLekx"

[programs.devnet]
stakan = "C5WmRvAk9BBWyg3uSEZ4EHtrNVn7jZu7qgykckXxLekx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/yury/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
